### ISSUE TITLE
Secure Payment Confirmation

### ISSUE THREAD

**Issue by cyberphone** [herrjemand/awesome-webauthn#45]
![fido-pay-li](https://user-images.githubusercontent.com/8044211/108576467-0f6dcf80-731e-11eb-8c02-48d461298cf6.png)
Yuriy, you need to add https://github.com/rsolomakhin/secure-payment-confirmation to your list of awesome webauthn stuff since it is targeted to be the future for secure on-line payments.

Personally I believe this is giant mistake created by a very small group of people but since it is powered by Google this is probably = FIDO, right?  _I'm not aware of any other payment effort that are betting on 3DS/step-up authentication_.

As you probably know EMV cards is the only real standard for secure payments.  However, EMV never made it on the Web (except by keying in card numbers...).  Therefore my suggestion is simply to create a Web-adapted version of EMV that unlike EMV also can work with most other payment networks including the EURO-zone's SEPA.  That is, the proposed system is even more universal than EMV.  The concept has been extensively tested but not with FIDO because that requires browser support.

**Comment by herrjemand** [comment]
@cyberphone yeah. Feel free to submit PR
