### ISSUE TITLE
Hardware devices missing...

### ISSUE THREAD

**Issue by noseshimself** [herrjemand/awesome-webauthn#51]
The section on hardware authenticators is quite empty

Basically everything Feitian, OnlyKey, Hapersecu, the  Yubi stuff and similar things are missing. Not to talk about all the obscure Chinese "works but nobody can tell you how safe they are" USB devices.

**Comment by aseigler** [comment]
That's because this list is focused on open source.

**Comment by herrjemand** [comment]
@noseshimself Yes, as @aseigler said. This project is about open source *)

Closing without action.
