### ISSUE TITLE
go: duo webauthn natural successor

### ISSUE THREAD

**Issue by james-d-elliott** [herrjemand/awesome-webauthn#74]
Hey there! The library [github.com/duo-labs/webauthn](https://github.com/duo-labs/webauthn) has been archived ([see here](https://github.com/duo-labs/webauthn#this-library-is-deprecated)) and replaced by [github.com/go-webauthn/webauthn](https://github.com/go-webauthn/webauthn). I am the principal maintainer of this org. With the help of several users this library now supports MDS3 (original only supports MDS2).

 It should theoretically be as conformant as the original as it's a direct fork with mostly bug fixes and sensible feature additions, though we have not expressly completed any conformance testing.
 
 How would you like to proceed with this? Would you like me to mark the original as deprecated (and how would you like this to appear) and add [github.com/go-webauthn/webauthn](https://github.com/go-webauthn/webauthn) under it as conformant or not mark it as such until we've completed formal conformance testing? Or do you want to handle this yourself?

**Comment by herrjemand** [comment]
@james-d-elliott Great! Could you open PR to replace it?
