### ISSUE TITLE
Add OpenAPI spec

### ISSUE THREAD

**Issue by Southclaws** [herrjemand/awesome-webauthn#79]
Hi! Not a request but more of a todo list item for me. I have a fully conformant OpenAPI spec for WebAuthn painstakingly copied from the official specification. I'm keen to pull this out into its own resource so it can be valuable for others to use. Let me know if that would be useful and I can get it up into a standalone repo and maybe linked here in the coming weeks.

The WebAuthn API spec itself is buried inside the Storyden API spec for anyone who finds this via Google search: https://github.com/Southclaws/storyden/blob/main/api/openapi.yaml#L1107-L1333

**Comment by herrjemand** [comment]
WebAuthn server integration is always nuanced. Everyone doing it their way. For conformance testing FIDO has its own API, but everyone doing it their way.

**Comment by Southclaws** [comment]
Yes but the spec itself is pretty solid and now that it's an implemented standard, the spec is unlikely to change in a drastic way. So an OpenAPI spec that defines all of the data structures in a conformant way provides value as it allows implementors on either side (client or server) to generate code for their bespoke implementations. An OpenAPI spec is just the data structure schemas, not the logic so it's quite useful to share.
