### ISSUE TITLE
Android 14 native app passkey example

### ISSUE THREAD

**Issue by irew** [herrjemand/awesome-webauthn#84]
Would it be appropriate to link to this repo?

https://github.com/Dashlane/android-passkey-example

It's a demo app for Android 14 that allows testing passkey registration and authentication.

**Comment by herrjemand** [comment]
This is a marketing page about passkeys and webauthn? @irew

**Comment by herrjemand** [comment]
@irew yeah, that looks good. Feel free to open PR *)

**Comment by irew** [comment]
Done https://github.com/herrjemand/awesome-webauthn/pull/86 👍🏽
