### ISSUE TITLE
WebAuthn.Net - open source .NET server library

### ISSUE THREAD

**Issue by vanbukin** [herrjemand/awesome-webauthn#95]
My team and I have developed the [WebAuthn.Net](https://github.com/dodobrands/WebAuthn.Net) library for the .NET ecosystem. 
It is open source under the [MIT license](https://github.com/dodobrands/WebAuthn.Net/blob/main/LICENSE) and serves as an alternative to [fido2-net-lib](https://github.com/passwordless-lib/fido2-net-lib). 
Our library passes all FIDO2 Server - MDS3 Tests (including all optional parameters) in the FIDO Conformance Tool 1.7.17. 
We have submitted the test results using this tool. 
The library includes a [demonstration host and instructions](https://github.com/dodobrands/WebAuthn.Net/tree/main/demo/WebAuthn.Net.Demo.FidoConformance) on how to perform similar tests independently (if someone does not trust our results, they can perform a similar verification on their own).

I would like to know how we can be included in the [Server Libraries](https://github.com/herrjemand/awesome-webauthn?tab=readme-ov-file#server-libraries) list, and is there anything else we need to do for our library to be marked as `FIDO CONFORMANT` in this list? 
Is it enough to make a PR to this repository, or are there any additional verification steps required?

**Comment by vanbukin** [comment]
@herrjemand

**Comment by herrjemand** [comment]
@vanbukin drop me a screenshot of passing tests and then feel free to do PR *)

**Comment by vanbukin** [comment]
![image](https://github.com/herrjemand/awesome-webauthn/assets/22099558/8c750d6d-5ea2-496e-ba48-cff36857f407)

**Comment by vanbukin** [comment]
#96
